#!/bin/sh
CLASSPATH=circumspec.jar:test:features

for f in lib/*.jar; do
    CLASSPATH=$CLASSPATH:$f
done

java $@ -Xmx1G -cp $CLASSPATH clojure.main -e "(use 'circumspec.runner) (run-tests-and-exit)"